filter:
  annotations:
    certificate-syncer-enabled: "true"
    certificate-syncer-dryRun: "false"

remap:
  - name: tls.crt
    value: '{{secretName}}.crt'
  - name: tls.key
    value: '{{secretName}}.crt.key'
